### ISSUE TITLE
Option: SOURCE_DIR to be able to output absolute paths to files in report XML

### ISSUE THREAD

**Issue by olleolleolle** [mila-labs/jshint-checkstyle-file-reporter#1]
Introduce an option SOURCE_DIR which can be fed to this plugin in the same way that JSHINT_CHECKSTYLE_FILE is passed in the env.

That would fix the issue experienced in another jshint Jenkins reporter: 

https://github.com/sublimeye/jshint-jenkins-checkstyle-reporter/issues/2

(That issue also contains a workaround.)

(It seems that the root of this is that jshint outputs relative file paths in its warnings. If it didn't, this would not be a problem.)

**Comment by mweibel** [comment]
Hi,

feel free to send us a pull request with the wished changes.

Best,
Michael
